### PR TITLE
Pin intake-esm

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@conda-forge-admin, please rerender

**Comment by aulemahal** [comment]
I'm not sure I understand.
I thought https://github.com/conda-forge/intake-esm-feedstock/pull/32 would make this pin non necessary ? Is there something that can be done by the intake-esm folks to solve this issue ?

**Comment by Zeitsperre** [comment]
I think they would need to yank their first build, since Python3.9 solvers will always grab the broken one. Would you want to follow up with them?

**Comment by Zeitsperre** [comment]
Closed via https://github.com/conda-forge/admin-requests/pull/935

**Pull request closed without merging**
